#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/downloads/{complete,incomplete} /watch

# copy config
[[ ! -f /config/settings.json ]] && cp \
	/defaults/settings.json /config/settings.json

# copy blocklist-update script
[[ ! -f /config/blocklist-update.sh ]] && cp \
	/defaults/blocklist-update.sh /config/blocklist-update.sh

# permissions
chown abc:abc \
	/config/settings.json \
	/config/blocklist-update.sh \
	/downloads \
	/downloads/complete \
	/downloads/incomplete \
	/watch

chmod 755 /config/blocklist-update.sh

#Bind Transmission to interface if specified by user
if [[ $BINDIFACE ]]; then
	IP=`ip -f inet -o addr show ${BINDIFACE}|cut -d\  -f 7 | cut -d/ -f 1`
	sed -i "s/\"bind-address-ipv4\": \(.*\)/\"bind-address-ipv4\": \"${IP}\",/g" /config/settings.json
fi
